apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot-backend
        image: surya0610/backend-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: employee
          - name: DB_USERNAME
            value: test
          - name: DB_PASSWORD
            value: testuser
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: springboot-backend
  type: NodePort

